# Generated by Django 5.1.3 on 2024-11-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checker",
            name="position_signatures",
            field=models.JSONField(default=dict),
        ),
    ]
