# Generated by Django 5.1.3 on 2024-11-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checker",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_use", "In Use"),
                    ("completed", "Completed"),
                ],
                default="new",
                max_length=10,
            ),
        ),
    ]
