# Generated by Django 4.2.16 on 2024-12-07 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='compensating_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_compensating', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='compensating_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferreceipt',
            name='compensating_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_compensating', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transferreceipt',
            name='compensating_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
