# Generated by Django 4.2.16 on 2024-12-07 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreceipt',
            name='bank_account',
            field=models.ForeignKey(
                null=True,
                blank=True,
                to='testapp.bankaccount',
                on_delete=django.db.models.deletion.SET_NULL,
            ),
        ),
        migrations.AlterField(
            model_name='transferreceipt',
            name='bank_account',
            field=models.ForeignKey(
                null=True,
                blank=True,
                to='testapp.bankaccount',
                on_delete=django.db.models.deletion.SET_NULL,
            ),
        ),
        migrations.AlterField(
            model_name='lcn',
            name='bank_account',
            field=models.ForeignKey(
                null=True,
                blank=True,
                to='testapp.bankaccount',
                on_delete=django.db.models.deletion.SET_NULL,
            ),
        ),
        migrations.AlterField(
            model_name='checkreceipt',
            name='bank_account',
            field=models.ForeignKey(
                null=True,
                blank=True,
                to='testapp.bankaccount',
                on_delete=django.db.models.deletion.SET_NULL,
            ),
        ),
    ]