# Generated by Django 4.2.16 on 2024-11-30 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_client_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_code',
            field=models.CharField(default=12345, max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{5,8}$', 'Client code must be numeric and between 5 and 8 digits.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='accounting_code',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Accounting code must start with 3 and be 5-7 digits long', regex='^3\\d{4,6}$')]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='ice_code',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='ICE code must be exactly 15 digits', regex='^\\d{15}$')]),
        ),
    ]
