# Generated by Django 5.1.3 on 2024-11-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0002_check_rejected_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="check",
            name="received_notes",
            field=models.TextField(blank=True),
        ),
    ]
