# Generated by Django 4.2.16 on 2024-12-07 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_cashreceipt_compensating_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsale',
            name='sale_type',
            field=models.CharField(choices=[('BRICKS', 'Bricks'), ('TRANSPORT', 'Transport')], default='BRICKS', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientsale',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clientsale',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.client'),
        ),
    ]
