# Generated by Django 5.1.3 on 2024-11-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0002_checker_position_signatures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="position",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
