# Generated by Django 4.2.16 on 2024-11-30 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_client_client_code_alter_entity_accounting_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name'], 'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.CharField(help_text='Enter a unique 5-10 digit code', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Client code must be at least 5 digits'), django.core.validators.MaxLengthValidator(10, 'Client code cannot exceed 10 digits'), django.core.validators.RegexValidator(message='Client code must contain only digits', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[a-zA-Z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='accounting_code',
            field=models.CharField(help_text='Enter 5-7 digits starting with 3', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Accounting code must start with 3 and be 5-7 digits long', regex='^3\\d{4,6}$')]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='ice_code',
            field=models.CharField(help_text='Enter exactly 15 digits', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='ICE code must be exactly 15 digits', regex='^\\d{15}$')]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[a-zA-Z\\s]*$')]),
        ),
    ]
