# Generated by Django 5.1.3 on 2024-11-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0003_check_received_at_check_received_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="signatures",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="check",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("printed", "Printed"),
                    ("ready_to_sign", "Ready to Sign"),
                    ("pending", "Pending"),
                    ("delivered", "Delivered"),
                    ("paid", "Paid"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
