# Generated by Django 4.2.16 on 2024-12-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_clientsale_sale_type_alter_clientsale_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationreceipt',
            name='presentation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('DISCOUNTED', 'Discounted'), ('COMPENSATED', 'Compensated')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='presentationreceipt',
            name='rejection_cause',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='presentationreceipt',
            name='status_locked',
            field=models.BooleanField(default=False),
        ),
    ]
