# Generated by Django 4.2.16 on 2024-11-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
