# Generated by Django 4.2.16 on 2024-11-30 18:39

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_client_options_alter_entity_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('client_year', models.IntegerField()),
                ('client_month', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PORTFOLIO', 'In Portfolio'), ('PRESENTED_COLLECTION', 'Presented for Collection'), ('PRESENTED_DISCOUNT', 'Presented for Discount'), ('DISCOUNTED', 'Discounted'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('COMPENSATED', 'Compensated')], default='PORTFOLIO', max_length=20)),
                ('check_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.bankaccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.client')),
                ('compensates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensated_by', to='testapp.checkreceipt')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.entity')),
            ],
            options={
                'verbose_name': 'Check',
                'verbose_name_plural': 'Checks',
            },
        ),
        migrations.CreateModel(
            name='LCN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('client_year', models.IntegerField()),
                ('client_month', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PORTFOLIO', 'In Portfolio'), ('PRESENTED_COLLECTION', 'Presented for Collection'), ('PRESENTED_DISCOUNT', 'Presented for Discount'), ('DISCOUNTED', 'Discounted'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('COMPENSATED', 'Compensated')], default='PORTFOLIO', max_length=20)),
                ('lcn_number', models.CharField(max_length=50)),
                ('issuing_bank', models.CharField(max_length=100)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.bankaccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.client')),
                ('compensates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensated_by', to='testapp.lcn')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.entity')),
            ],
            options={
                'verbose_name': 'LCN',
                'verbose_name_plural': 'LCNs',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presentation_type', models.CharField(choices=[('COLLECTION', 'Collection'), ('DISCOUNT', 'Discount')], max_length=10)),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.bankaccount')),
            ],
            options={
                'verbose_name': 'Presentation',
                'verbose_name_plural': 'Presentations',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('client_year', models.IntegerField()),
                ('client_month', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('transfer_reference', models.CharField(max_length=100)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.bankaccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.client')),
                ('credited_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_receipts', to='testapp.bankaccount')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.entity')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
            },
        ),
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('client_year', models.IntegerField()),
                ('client_month', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.bankaccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.client')),
                ('credited_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipts', to='testapp.bankaccount')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.entity')),
            ],
            options={
                'verbose_name': 'Cash Receipt',
                'verbose_name_plural': 'Cash Receipts',
            },
        ),
        migrations.CreateModel(
            name='PresentationReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('checkreceipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_presentations', to='testapp.checkreceipt')),
                ('lcn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcn_presentations', to='testapp.lcn')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_receipts', to='testapp.presentation')),
            ],
            options={
                'verbose_name': 'Presentation Receipt',
                'verbose_name_plural': 'Presentation Receipts',
                'unique_together': {('presentation', 'lcn'), ('presentation', 'checkreceipt')},
            },
        ),
    ]
