# Generated by Django 4.2.16 on 2024-12-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_presentationreceipt_presentation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationreceipt',
            name='presentation_status',
        ),
        migrations.RemoveField(
            model_name='presentationreceipt',
            name='rejection_cause',
        ),
        migrations.RemoveField(
            model_name='presentationreceipt',
            name='status_locked',
        ),
        migrations.AddField(
            model_name='presentationreceipt',
            name='immutable',
            field=models.BooleanField(default=False),
        ),
    ]
