# Generated by Django 4.2.16 on 2024-12-13 00:31

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_interbanktransfer_transferredrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankFeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('accounting_code', models.CharField(max_length=5)),
                ('vat_code', models.CharField(max_length=5)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankFeeTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('raw_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=4, null=True)),
                ('vat_included', models.BooleanField(default=False)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.bankaccount')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.bankfeetype')),
                ('related_presentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.presentation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
