# Generated by Django 4.2.16 on 2024-12-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_remove_presentationreceipt_presentation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationreceipt',
            name='rejection_cause',
            field=models.CharField(blank=True, choices=[('INSUFFICIENT_FUNDS', 'Insufficient Funds'), ('ACCOUNT_CLOSED', 'Account Closed/Frozen'), ('SIGNATURE_MISMATCH', 'Signature Mismatch'), ('INVALID_DATE', 'Date Invalid/Post-dated'), ('AMOUNT_DISCREPANCY', 'Amount Discrepancy'), ('TECHNICAL_ERROR', 'Technical Error (MICR)'), ('STOP_PAYMENT', 'Stop Payment Order'), ('ACCOUNT_ERROR', 'Account Number Error'), ('FORMAL_DEFECT', 'Formal Defect'), ('BANK_ERROR', 'Bank Processing Error')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='presentationreceipt',
            name='status',
            field=models.CharField(choices=[('PORTFOLIO', 'In Portfolio'), ('PRESENTED_COLLECTION', 'Presented for Collection'), ('PRESENTED_DISCOUNT', 'Presented for Discount'), ('DISCOUNTED', 'Discounted'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('COMPENSATED', 'Compensated'), ('UNPAID', 'Unpaid')], default='PORTFOLIO', max_length=20),
        ),
    ]
