# Generated by Django 4.2.16 on 2024-12-01 13:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_checkreceipt_lcn_presentation_transferreceipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.client')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
