# Generated by Django 4.2.16 on 2024-12-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_presentationreceipt_rejection_cause_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationreceipt',
            name='rejection_cause',
        ),
        migrations.RemoveField(
            model_name='presentationreceipt',
            name='status',
        ),
        migrations.AddField(
            model_name='presentationreceipt',
            name='recorded_status',
            field=models.CharField(blank=True, choices=[('PORTFOLIO', 'In Portfolio'), ('PRESENTED_COLLECTION', 'Presented for Collection'), ('PRESENTED_DISCOUNT', 'Presented for Discount'), ('DISCOUNTED', 'Discounted'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('COMPENSATED', 'Compensated'), ('UNPAID', 'Unpaid')], help_text='Stores the final status decision made in this presentation', max_length=20, null=True),
        ),
    ]
