# Generated by Django 4.2.16 on 2024-12-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_bankfeetype_created_at_bankfeetype_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkreceipt',
            name='unpaid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lcn',
            name='unpaid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
