# Generated by Django 4.2.16 on 2024-12-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_clientsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='presentation',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='presentations/'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('presented', 'Presented'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
