# Generated by Django 4.2.16 on 2024-12-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_checkreceipt_unpaid_date_lcn_unpaid_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipthistory',
            options={'ordering': ['-business_date', '-timestamp'], 'verbose_name': 'Receipt History', 'verbose_name_plural': 'Receipt Histories'},
        ),
        migrations.AddField(
            model_name='receipthistory',
            name='business_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
