# Generated by Django 4.2.16 on 2024-11-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_invoice_payment_due_date_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fiscal_label',
            field=models.CharField(default='TEST', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='vat_rate',
            field=models.DecimalField(choices=[(0.0, '0%'), (7.0, '7%'), (10.0, '10%'), (11.0, '11%'), (14.0, '14%'), (16.0, '16%'), (20.0, '20%')], decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(choices=[(0.0, '0%'), (7.0, '7%'), (10.0, '10%'), (11.0, '11%'), (14.0, '14%'), (16.0, '16%'), (20.0, '20%')], decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
