# Generated by Django 4.2.16 on 2024-12-21 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_alter_receipthistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkreceipt',
            name='check_number',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\d+$', 'Check number must contain only digits.')]),
        ),
        migrations.AlterField(
            model_name='lcn',
            name='lcn_number',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\d+$', 'LCN number must contain only digits.')]),
        ),
        migrations.AddConstraint(
            model_name='checkreceipt',
            constraint=models.UniqueConstraint(fields=('check_number', 'issuing_bank', 'entity'), name='unique_check_number_per_bank_entity'),
        ),
        migrations.AddConstraint(
            model_name='lcn',
            constraint=models.UniqueConstraint(fields=('lcn_number', 'issuing_bank', 'entity'), name='unique_lcn_number_per_bank_entity'),
        ),
    ]
