# Generated by Django 4.2.16 on 2024-11-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_product_fiscal_label_alter_invoiceproduct_vat_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='fiscal_label',
        ),
    ]
