# Generated by Django 4.2.16 on 2024-12-04 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('testapp', '0008_remove_checkreceipt_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkreceipt',
            name='compensating_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_compensating', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='checkreceipt',
            name='compensating_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkreceipt',
            name='compensation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkreceipt',
            name='rejection_cause',
            field=models.CharField(blank=True, choices=[('INSUFFICIENT_FUNDS', 'Insufficient Funds'), ('ACCOUNT_CLOSED', 'Account Closed/Frozen'), ('SIGNATURE_MISMATCH', 'Signature Mismatch'), ('INVALID_DATE', 'Date Invalid/Post-dated'), ('AMOUNT_DISCREPANCY', 'Amount Discrepancy'), ('TECHNICAL_ERROR', 'Technical Error (MICR)'), ('STOP_PAYMENT', 'Stop Payment Order'), ('ACCOUNT_ERROR', 'Account Number Error'), ('FORMAL_DEFECT', 'Formal Defect'), ('BANK_ERROR', 'Bank Processing Error')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lcn',
            name='compensating_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_compensating', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='lcn',
            name='compensating_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lcn',
            name='compensation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lcn',
            name='rejection_cause',
            field=models.CharField(blank=True, choices=[('INSUFFICIENT_FUNDS', 'Insufficient Funds'), ('ACCOUNT_CLOSED', 'Account Closed/Frozen'), ('SIGNATURE_MISMATCH', 'Signature Mismatch'), ('INVALID_DATE', 'Date Invalid/Post-dated'), ('AMOUNT_DISCREPANCY', 'Amount Discrepancy'), ('TECHNICAL_ERROR', 'Technical Error (MICR)'), ('STOP_PAYMENT', 'Stop Payment Order'), ('ACCOUNT_ERROR', 'Account Number Error'), ('FORMAL_DEFECT', 'Formal Defect'), ('BANK_ERROR', 'Bank Processing Error')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkreceipt',
            name='status',
            field=models.CharField(choices=[('PORTFOLIO', 'In Portfolio'), ('PRESENTED_COLLECTION', 'Presented for Collection'), ('PRESENTED_DISCOUNT', 'Presented for Discount'), ('DISCOUNTED', 'Discounted'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('COMPENSATED', 'Compensated'), ('UNPAID', 'Unpaid')], default='PORTFOLIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='lcn',
            name='status',
            field=models.CharField(choices=[('PORTFOLIO', 'In Portfolio'), ('PRESENTED_COLLECTION', 'Presented for Collection'), ('PRESENTED_DISCOUNT', 'Presented for Discount'), ('DISCOUNTED', 'Discounted'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('COMPENSATED', 'Compensated'), ('UNPAID', 'Unpaid')], default='PORTFOLIO', max_length=20),
        ),
    ]
