# Generated by Django 4.2.16 on 2024-12-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_bankaccount_bank_overdraft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_overdraft',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='check_discount_line_amount',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='has_check_discount_line',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='has_lcn_discount_line',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='lcn_discount_line_amount',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='overdraft_fee',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='stamp_fee_per_receipt',
        ),
    ]
