# Generated by Django 4.2.16 on 2024-12-21 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('testapp', '0009_alter_checkreceipt_check_number_alter_lcn_lcn_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkreceipt',
            name='status',
            field=models.CharField(choices=[('PORTFOLIO', 'In Portfolio'), ('PRESENTED_COLLECTION', 'Presented for Collection'), ('PRESENTED_DISCOUNT', 'Presented for Discount'), ('DISCOUNTED', 'Discounted'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('COMPENSATED', 'Compensated'), ('PARTIALLY_COMPENSATED', 'Partially Compensated'), ('UNPAID', 'Unpaid')], default='PORTFOLIO', max_length=25),
        ),
        migrations.AlterField(
            model_name='lcn',
            name='status',
            field=models.CharField(choices=[('PORTFOLIO', 'In Portfolio'), ('PRESENTED_COLLECTION', 'Presented for Collection'), ('PRESENTED_DISCOUNT', 'Presented for Discount'), ('DISCOUNTED', 'Discounted'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('COMPENSATED', 'Compensated'), ('PARTIALLY_COMPENSATED', 'Partially Compensated'), ('UNPAID', 'Unpaid')], default='PORTFOLIO', max_length=25),
        ),
        migrations.AlterField(
            model_name='presentationreceipt',
            name='recorded_status',
            field=models.CharField(blank=True, choices=[('PORTFOLIO', 'In Portfolio'), ('PRESENTED_COLLECTION', 'Presented for Collection'), ('PRESENTED_DISCOUNT', 'Presented for Discount'), ('DISCOUNTED', 'Discounted'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('COMPENSATED', 'Compensated'), ('PARTIALLY_COMPENSATED', 'Partially Compensated'), ('UNPAID', 'Unpaid')], help_text='Stores the final status decision made in this presentation', max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='CompensationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_id', models.UUIDField()),
                ('compensating_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('compensation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('compensating_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensating_records', to='contenttypes.contenttype')),
                ('receipt_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensated_records', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Compensation Record',
                'verbose_name_plural': 'Compensation Records',
                'ordering': ['-compensation_date'],
            },
        ),
    ]
