# Generated by Django 4.2.16 on 2024-12-05 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0009_checkreceipt_compensating_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('action', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('presented', 'Presented'), ('compensated', 'Compensated'), ('compensation_paid', 'Compensation Paid')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt History',
                'verbose_name_plural': 'Receipt Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
