# Generated by Django 4.2.16 on 2024-12-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_make_bank_account_nullable'),
        ('testapp', '0010_remove_invoice_unique_supplier_invoice_ref_and_more'),
    ]

    operations = [
    ]
