# Generated by Django 5.1.3 on 2024-12-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0010_receipthistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipthistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("status_changed", "Status Changed"),
                    ("presented_collection", "Presented for Collection"),
                    ("presented_discount", "Presented for Discount"),
                    ("compensating_assigned", "Compensating Receipt Assigned"),
                    ("compensated", "Compensated"),
                    ("unpaid", "Marked as Unpaid"),
                    ("paid", "Paid"),
                    ("rejected", "Rejected by Bank"),
                ],
                max_length=50,
            ),
        ),
    ]
