# Generated by Django 4.2.16 on 2024-12-22 11:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('testapp', '0013_alter_checkreceipt_status_alter_lcn_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashreceipt',
            name='compensating_content_type',
        ),
        migrations.RemoveField(
            model_name='cashreceipt',
            name='compensating_object_id',
        ),
        migrations.RemoveField(
            model_name='checkreceipt',
            name='compensates',
        ),
        migrations.RemoveField(
            model_name='checkreceipt',
            name='compensating_content_type',
        ),
        migrations.RemoveField(
            model_name='checkreceipt',
            name='compensating_object_id',
        ),
        migrations.RemoveField(
            model_name='checkreceipt',
            name='compensation_date',
        ),
        migrations.RemoveField(
            model_name='checkreceipt',
            name='rejection_cause',
        ),
        migrations.RemoveField(
            model_name='checkreceipt',
            name='unpaid_date',
        ),
        migrations.RemoveField(
            model_name='lcn',
            name='compensates',
        ),
        migrations.RemoveField(
            model_name='lcn',
            name='compensating_content_type',
        ),
        migrations.RemoveField(
            model_name='lcn',
            name='compensating_object_id',
        ),
        migrations.RemoveField(
            model_name='lcn',
            name='compensation_date',
        ),
        migrations.RemoveField(
            model_name='lcn',
            name='rejection_cause',
        ),
        migrations.RemoveField(
            model_name='lcn',
            name='unpaid_date',
        ),
        migrations.RemoveField(
            model_name='transferreceipt',
            name='compensating_content_type',
        ),
        migrations.RemoveField(
            model_name='transferreceipt',
            name='compensating_object_id',
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('printed', 'Printed'), ('ready_to_sign', 'Ready to Sign'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=25),
        ),
        migrations.AlterField(
            model_name='checkreceipt',
            name='status',
            field=models.CharField(choices=[('PORTFOLIO', 'In Portfolio'), ('PRESENTED_COLLECTION', 'Presented for Collection'), ('PRESENTED_DISCOUNT', 'Presented for Discount'), ('DISCOUNTED', 'Discounted'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('COMPENSATED', 'Compensated'), ('UNPAID', 'Unpaid'), ('PARTIALLY_COMPENSATED', 'Partially Compensated')], default='PORTFOLIO', max_length=25),
        ),
        migrations.AlterField(
            model_name='entity',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='not_paid', max_length=25),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Finalized'), ('paid', 'Paid')], default='draft', max_length=25),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit Note')], default='invoice', max_length=25),
        ),
        migrations.AlterField(
            model_name='lcn',
            name='status',
            field=models.CharField(choices=[('PORTFOLIO', 'In Portfolio'), ('PRESENTED_COLLECTION', 'Presented for Collection'), ('PRESENTED_DISCOUNT', 'Presented for Discount'), ('DISCOUNTED', 'Discounted'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('COMPENSATED', 'Compensated'), ('UNPAID', 'Unpaid'), ('PARTIALLY_COMPENSATED', 'Partially Compensated')], default='PORTFOLIO', max_length=25),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('presented', 'Presented'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='presentationreceipt',
            name='recorded_status',
            field=models.CharField(blank=True, choices=[('PORTFOLIO', 'In Portfolio'), ('PRESENTED_COLLECTION', 'Presented for Collection'), ('PRESENTED_DISCOUNT', 'Presented for Discount'), ('DISCOUNTED', 'Discounted'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('COMPENSATED', 'Compensated'), ('UNPAID', 'Unpaid'), ('PARTIALLY_COMPENSATED', 'Partially Compensated')], help_text='Stores the final status decision made in this presentation', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='expense_code',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[0-9]{5,}$', 'Expense code must be numeric and at least 5 characters long.')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='accounting_code',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{5,}$', 'Expense code must be numeric and at least 5 characters long.')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='if_code',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='rc_code',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')]),
        ),
        migrations.CreateModel(
            name='CompensationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compensated_id', models.UUIDField()),
                ('compensator_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=False)),
                ('compensated_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensated_records', to='contenttypes.contenttype')),
                ('compensator_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensator_records', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
