# Generated by Django 4.2.16 on 2024-12-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_remove_cashreceipt_compensating_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkreceipt',
            name='rejection_cause',
            field=models.CharField(blank=True, choices=[('INSUFFICIENT_FUNDS', 'Insufficient Funds'), ('ACCOUNT_CLOSED', 'Account Closed/Frozen'), ('SIGNATURE_MISMATCH', 'Signature Mismatch'), ('INVALID_DATE', 'Date Invalid/Post-dated'), ('AMOUNT_DISCREPANCY', 'Amount Discrepancy'), ('TECHNICAL_ERROR', 'Technical Error (MICR)'), ('STOP_PAYMENT', 'Stop Payment Order'), ('ACCOUNT_ERROR', 'Account Number Error'), ('FORMAL_DEFECT', 'Formal Defect'), ('BANK_ERROR', 'Bank Processing Error')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkreceipt',
            name='unpaid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lcn',
            name='rejection_cause',
            field=models.CharField(blank=True, choices=[('INSUFFICIENT_FUNDS', 'Insufficient Funds'), ('ACCOUNT_CLOSED', 'Account Closed/Frozen'), ('SIGNATURE_MISMATCH', 'Signature Mismatch'), ('INVALID_DATE', 'Date Invalid/Post-dated'), ('AMOUNT_DISCREPANCY', 'Amount Discrepancy'), ('TECHNICAL_ERROR', 'Technical Error (MICR)'), ('STOP_PAYMENT', 'Stop Payment Order'), ('ACCOUNT_ERROR', 'Account Number Error'), ('FORMAL_DEFECT', 'Formal Defect'), ('BANK_ERROR', 'Bank Processing Error')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lcn',
            name='unpaid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
