# Generated by Django 4.2.16 on 2024-12-23 19:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_checkreceipt_rejection_cause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationreceipt',
            name='forecast_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentationreceipt',
            name='is_forecasted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ForecastStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('label', models.CharField(max_length=255)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reference', models.CharField(max_length=100)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.UUIDField()),
                ('is_processed', models.BooleanField(default=False)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.bankaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
