# Generated by Django 4.2.16 on 2024-12-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_presentationreceipt_forecast_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecaststatement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
