# Generated by Django 4.2.16 on 2024-12-31 19:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_forecaststatement_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_indefinite', models.BooleanField(default=False)),
                ('periodicity', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Biannual'), ('annual', 'Annual')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('generation_day', models.PositiveIntegerField(help_text='Day of month to generate invoice (1-28)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('cancellation_date', models.DateField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='receipthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('presented_collection', 'Presented for Collection'), ('presented_discount', 'Presented for Discount'), ('compensating_assigned', 'Compensating Receipt Assigned'), ('compensated', 'Compensation Allocated'), ('unpaid', 'Marked as Unpaid'), ('paid', 'Paid'), ('rejected', 'Rejected by Bank')], max_length=50),
        ),
        migrations.CreateModel(
            name='ContractProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reduction_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='testapp.contract')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.product')),
            ],
            options={
                'unique_together': {('contract', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ContractInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.contract')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='testapp.invoice')),
            ],
            options={
                'unique_together': {('contract', 'period_start', 'period_end')},
            },
        ),
    ]
