# Generated by Django 4.2.16 on 2025-01-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_check_is_supplier_payment_alter_check_cause_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='check',
            name='check_amount_cannot_exceed_due',
        ),
        migrations.AddConstraint(
            model_name='check',
            constraint=models.CheckConstraint(check=models.Q(('is_supplier_payment', True), ('amount__lte', models.F('amount_due')), _connector='OR'), name='check_amount_cannot_exceed_due'),
        ),
    ]
