# Generated by Django 4.2.16 on 2025-01-04 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0020_remove_check_check_amount_cannot_exceed_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='delay_check',
            field=models.IntegerField(default=0, help_text='Number of days to delay check payment forecasts after due date', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='delay_lcn',
            field=models.IntegerField(default=0, help_text='Number of days to delay LCN payment forecasts after due date', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
