# Generated by Django 4.2.16 on 2025-01-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_supplier_delay_check_supplier_delay_lcn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='delay_check',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='delay_lcn',
        ),
    ]
