# Generated by Django 4.2.16 on 2025-01-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0023_supplier_delay_check_supplier_delay_lcn'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
