# Generated by Django 4.2.16 on 2025-01-11 11:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0024_check_printed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='domiciliation_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domiciled_contracts', to='testapp.bankaccount'),
        ),
        migrations.AddField(
            model_name='contract',
            name='domiciliation_day',
            field=models.PositiveIntegerField(blank=True, help_text='Day of month for domiciled payment (1-28)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_domiciled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('organism_type', models.CharField(choices=[('TAX', 'Tax'), ('SOCIAL', 'Social Obligation'), ('OTHER', 'Other')], max_length=10)),
                ('accounting_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', 'Must be numeric')])),
                ('periodicity', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Biannual'), ('annual', 'Annual')], max_length=20)),
                ('due_day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('domiciliation_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domiciled_organisms', to='testapp.bankaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
