# Generated by Django 4.2.16 on 2025-01-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0025_contract_domiciliation_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='domiciliation_bank',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='domiciliation_day',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='is_domiciled',
        ),
        migrations.DeleteModel(
            name='Organism',
        ),
    ]
