# Generated by Django 4.2.16 on 2025-01-11 16:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0026_remove_contract_domiciliation_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='domiciliation_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domiciled_contracts', to='testapp.bankaccount'),
        ),
        migrations.AddField(
            model_name='contract',
            name='domiciliation_day',
            field=models.IntegerField(blank=True, help_text='Day of month for domiciliation payment (1-28)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AddField(
            model_name='contract',
            name='domiciliation_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='domiciliation_suspension_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='domiciliation_suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_domiciled',
            field=models.BooleanField(default=False),
        ),
    ]
