# Generated by Django 4.2.16 on 2025-01-14 20:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0027_contract_domiciliation_bank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectDebit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('processed_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_cause', models.CharField(blank=True, choices=[('INSUFFICIENT_FUNDS', 'Insufficient Funds'), ('ACCOUNT_CLOSED', 'Account Closed/Frozen'), ('TECHNICAL_ERROR', 'Technical Error'), ('STOP_PAYMENT', 'Stop Payment Order'), ('BANK_ERROR', 'Bank Processing Error')], max_length=50, null=True)),
                ('rejection_date', models.DateField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.bankaccount')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.contract')),
                ('forecast', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_debit', to='testapp.forecaststatement')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.contractinvoice')),
            ],
            options={
                'verbose_name': 'Direct Debit',
                'verbose_name_plural': 'Direct Debits',
                'ordering': ['due_date'],
            },
        ),
    ]
