# Generated by Django 4.2.16 on 2025-01-15 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0028_directdebit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractinvoice',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract_invoice', to='testapp.invoice'),
        ),
    ]
