# Generated by Django 4.2.16 on 2025-01-17 17:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0031_userrole_can_manage_bank_accounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directdebit',
            name='contract_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testapp.contractinvoice'),
        ),
        migrations.AddField(
            model_name='directdebit',
            name='is_supplier_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directdebit',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testapp.supplier'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testapp.contract'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testapp.invoice'),
        ),
        migrations.CreateModel(
            name='DirectDebitAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_debit_allocations', to='testapp.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='testapp.directdebit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='directdebitallocation',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='direct_debit_allocation_positive'),
        ),
    ]
