# Generated by Django 4.2.16 on 2025-01-18 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0032_directdebit_contract_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directdebit',
            name='contract_invoice',
        ),
        migrations.RemoveField(
            model_name='directdebit',
            name='is_supplier_payment',
        ),
        migrations.RemoveField(
            model_name='directdebit',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testapp.contractinvoice'),
        ),
        migrations.DeleteModel(
            name='DirectDebitAllocation',
        ),
    ]
