# Generated by Django 4.2.16 on 2025-01-19 19:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0033_remove_directdebit_contract_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('period_year', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('declared', 'Declared'), ('paid', 'Paid')], default='draft', max_length=10)),
                ('total_invoiced_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_deducted_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('due_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('forecast', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vat_declaration', to='testapp.forecaststatement')),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
            },
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='vat_declaration_period',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{4}$', 'Period must be in MM-YYYY format')]),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='vat_declared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='vat_declaration_period',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{4}$', 'Period must be in MM-YYYY format')]),
        ),
        migrations.AddField(
            model_name='check',
            name='vat_declared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkreceipt',
            name='vat_declaration_period',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{4}$', 'Period must be in MM-YYYY format')]),
        ),
        migrations.AddField(
            model_name='checkreceipt',
            name='vat_declared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directdebit',
            name='vat_declaration_period',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{4}$', 'Period must be in MM-YYYY format')]),
        ),
        migrations.AddField(
            model_name='directdebit',
            name='vat_declared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='non_deductible_vat',
            field=models.BooleanField(default=False, help_text='If true, VAT from this invoice cannot be deducted'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_deduction_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of VAT that can be deducted', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='lcn',
            name='vat_declaration_period',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{4}$', 'Period must be in MM-YYYY format')]),
        ),
        migrations.AddField(
            model_name='lcn',
            name='vat_declared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferreceipt',
            name='vat_declaration_period',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{4}$', 'Period must be in MM-YYYY format')]),
        ),
        migrations.AddField(
            model_name='transferreceipt',
            name='vat_declared',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VATDeclarationDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('receipt', 'Receipt Payment'), ('invoice_check', 'Invoice Check Payment'), ('invoice_direct_debit', 'Invoice Direct Debit')], max_length=20)),
                ('source_id', models.UUIDField()),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_deducted', models.BooleanField(default=False)),
                ('vat_rate', models.DecimalField(decimal_places=2, help_text='VAT rate for this entry', max_digits=5)),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Original amount before credits', max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit note amount', max_digits=15)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='testapp.vatdeclaration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VATConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('declaration_day', models.IntegerField(help_text='Day of month for VAT declaration (1-28)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('invoiced_vat_account', models.CharField(default='4300', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{4,5}$', 'Account code must be 4-5 digits')])),
                ('deducted_vat_account', models.CharField(default='4400', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{4,5}$', 'Account code must be 4-5 digits')])),
                ('journal', models.CharField(default='06', max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', 'Journal must be exactly 2 digits')])),
                ('domiciliation_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vat_declarations', to='testapp.bankaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='vatdeclaration',
            constraint=models.UniqueConstraint(fields=('period_month', 'period_year'), name='unique_vat_period'),
        ),
    ]
