# Generated by Django 4.2.16 on 2025-01-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0034_vatdeclaration_cashreceipt_vat_declaration_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='non_deductible_vat',
        ),
        migrations.AddField(
            model_name='product',
            name='non_deductible_vat',
            field=models.BooleanField(default=False, help_text='If true, VAT from this invoice cannot be deducted'),
        ),
    ]
