# Generated by Django 4.2.16 on 2025-01-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0035_remove_invoice_non_deductible_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='non_deductible_vat',
            field=models.BooleanField(default=False, help_text='If true, VAT from this invoice cannot be deducted'),
        ),
        migrations.AlterField(
            model_name='product',
            name='non_deductible_vat',
            field=models.BooleanField(default=False, help_text='If true, VAT from this product cannot be deducted'),
        ),
    ]
