# Generated by Django 4.2.16 on 2025-01-21 21:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0037_alter_invoice_vat_deduction_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='vat_deduction_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Percentage of VAT that can be deducted', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
