# Generated by Django 4.2.16 on 2025-01-24 22:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import testapp.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0038_alter_invoice_vat_deduction_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='doc_status',
            field=models.CharField(choices=[('ORIGINAL', 'Original'), ('COPY', 'Copy')], default='ORIGINAL', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=testapp.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), testapp.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('ENERGY', 'Energy'), ('INSURANCE', 'Insurance'), ('LEASING', 'Leasing'), ('UTILITIES', 'Water/Electricity'), ('TELECOM', 'Phone/Internet'), ('RENT', 'Rent'), ('SERVICE', 'Services'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='special_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReceptionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=testapp.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), testapp.models.validate_file_size])),
                ('notes', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_notes', to='testapp.supplier')),
            ],
            options={
                'ordering': ['-date', 'ref'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=testapp.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), testapp.models.validate_file_size])),
                ('notes', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_notes', to='testapp.supplier')),
            ],
            options={
                'ordering': ['-date', 'ref'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_notes',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='testapp.deliverynote'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reception_notes',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='testapp.receptionnote'),
        ),
        migrations.AddConstraint(
            model_name='receptionnote',
            constraint=models.UniqueConstraint(fields=('ref',), name='unique_reception_note_ref'),
        ),
        migrations.AddConstraint(
            model_name='deliverynote',
            constraint=models.UniqueConstraint(fields=('ref',), name='unique_delivery_note_ref'),
        ),
    ]
