# Generated by Django 4.2.16 on 2025-02-04 21:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0039_invoice_doc_status_invoice_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('period_year', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('declared', 'Declared'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('paid_by_check', models.BooleanField(default=False, help_text='If True, paid by check instead of direct debit')),
                ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('direct_debit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_declaration', to='testapp.directdebit')),
                ('forecast', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_declaration', to='testapp.forecaststatement')),
                ('payment_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pay_declarations', to='testapp.check')),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
            },
        ),
        migrations.CreateModel(
            name='PayItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('account_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{4,5}$', 'Account code must be 4-5 digits')])),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_debit', models.BooleanField(default=True, help_text='If True, amount is recorded as debit; if False, as credit')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='PayDeclarationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('account_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{4,5}$', 'Account code must be 4-5 digits')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_debit', models.BooleanField(default=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='testapp.paydeclaration')),
                ('template_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declaration_items', to='testapp.payitem')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='PayConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_day', models.PositiveIntegerField(help_text='Day of month to generate declaration (1-28)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('periodicity', models.CharField(choices=[('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('account_code', models.CharField(help_text='Main account code for pay operations', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{4,5}$', 'Account code must be 4-5 digits')])),
                ('journal_code', models.CharField(default='07', max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', 'Journal must be exactly 2 digits')])),
                ('domiciliation_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_declarations', to='testapp.bankaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='paydeclaration',
            constraint=models.UniqueConstraint(fields=('period_month', 'period_year'), name='unique_pay_period'),
        ),
    ]
