# Generated by Django 4.2.16 on 2025-02-07 19:34

import django.core.validators
from django.db import migrations, models
import testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0041_bankchecktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=testapp.models.get_receipt_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), testapp.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='checkreceipt',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=testapp.models.get_receipt_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), testapp.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='lcn',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=testapp.models.get_receipt_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), testapp.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='transferreceipt',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=testapp.models.get_receipt_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), testapp.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=testapp.models.get_receipt_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), testapp.models.validate_file_size]),
        ),
    ]
