# Generated by Django 4.2.16 on 2025-02-08 09:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0042_cashreceipt_document_checkreceipt_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrickType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('industrial_code', models.CharField(max_length=50, unique=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bricks_per_wagon', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyProductionMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_date', models.DateField(unique=True)),
                ('calculated_vpower', models.PositiveIntegerField(help_text='Automatically calculated industrial power (minutes)')),
                ('manual_vpower', models.PositiveIntegerField(blank=True, help_text='Manually set industrial power, overrides calculated value', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Daily Production Metrics',
                'verbose_name_plural': 'Daily Production Metrics',
                'ordering': ['-production_date'],
            },
        ),
        migrations.CreateModel(
            name='LoadingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loading_date', models.DateField()),
                ('bulk_quantity', models.PositiveIntegerField(default=0)),
                ('packaged_quantity', models.PositiveIntegerField(default=0)),
                ('bulk_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('packaged_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('brick_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.bricktype')),
            ],
            options={
                'ordering': ['-loading_date'],
            },
        ),
        migrations.CreateModel(
            name='BrickStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulk_quantity', models.PositiveIntegerField(default=0)),
                ('packaged_quantity', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('brick_type', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='testapp.bricktype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrickPriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_packaged', models.BooleanField(help_text='True for packaged bricks, False for bulk')),
                ('effective_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('brick_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='testapp.bricktype')),
            ],
            options={
                'ordering': ['-effective_date'],
                'get_latest_by': 'effective_date',
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_date', models.DateField()),
                ('wagons_produced', models.PositiveIntegerField()),
                ('bricks_packaged', models.PositiveIntegerField(default=0)),
                ('breakage', models.PositiveIntegerField(default=0)),
                ('miscellaneous_adjustment', models.IntegerField(default=0, help_text='Positive or negative adjustment to account for production anomalies')),
                ('notes', models.TextField(blank=True)),
                ('brick_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.bricktype')),
            ],
            options={
                'ordering': ['-production_date'],
                'unique_together': {('brick_type', 'production_date')},
            },
        ),
    ]
