# Generated by Django 4.2.16 on 2025-02-09 20:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0043_bricktype_dailyproductionmetrics_loadingrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Energy Type',
                'verbose_name_plural': 'Energy Types',
            },
        ),
        migrations.AlterUniqueTogether(
            name='productionbatch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='calculated_vpower',
            field=models.PositiveIntegerField(default=0, help_text='Automatically calculated industrial power (minutes)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='vpower',
            field=models.PositiveIntegerField(blank=True, help_text='Manual override for calculated VPower', null=True),
        ),
        migrations.CreateModel(
            name='EnergyPriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('energy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='testapp.energytype')),
            ],
            options={
                'ordering': ['-effective_date'],
                'get_latest_by': 'effective_date',
            },
        ),
        migrations.RemoveField(
            model_name='productionbatch',
            name='breakage',
        ),
        migrations.RemoveField(
            model_name='productionbatch',
            name='brick_type',
        ),
        migrations.RemoveField(
            model_name='productionbatch',
            name='bricks_packaged',
        ),
        migrations.RemoveField(
            model_name='productionbatch',
            name='miscellaneous_adjustment',
        ),
        migrations.RemoveField(
            model_name='productionbatch',
            name='wagons_produced',
        ),
        migrations.CreateModel(
            name='ProductionEnergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('energy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.energytype')),
                ('production_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_consumption', to='testapp.productionbatch')),
            ],
            options={
                'unique_together': {('production_batch', 'energy_type')},
            },
        ),
        migrations.CreateModel(
            name='BrickProduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wagons_produced', models.PositiveIntegerField()),
                ('miscellaneous_adjustment', models.IntegerField(default=0, help_text='Positive or negative adjustment to account for production anomalies')),
                ('bricks_packaged', models.PositiveIntegerField(default=0)),
                ('bulk_price_at_time', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('packaged_price_at_time', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('brick_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.bricktype')),
                ('production_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brick_productions', to='testapp.productionbatch')),
            ],
            options={
                'unique_together': {('production_batch', 'brick_type')},
            },
        ),
    ]
