# Generated by Django 4.2.16 on 2025-02-13 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0044_energytype_alter_productionbatch_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brickstock',
            name='brick_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='testapp.bricktype'),
        ),
    ]
