# Generated by Django 4.2.16 on 2025-02-13 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0045_alter_brickstock_brick_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='ice_code',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{15}$', 'ICE code must be exactly 15 digits')]),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='if_code',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('ENERGY', 'Energy'), ('INSURANCE', 'Insurance'), ('LEASING', 'Leasing'), ('UTILITIES', 'Water/Electricity'), ('TELECOM', 'Phone/Internet'), ('RENT', 'Rent'), ('SERVICE', 'Services'), ('LOAN', 'Bank Loan'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
