# Generated by Django 4.2.16 on 2025-02-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0046_bankaccount_ice_code_bankaccount_if_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='invoice_type',
            field=models.CharField(choices=[('ENERGY', 'Energy'), ('INSURANCE', 'Insurance'), ('LEASING', 'Leasing'), ('UTILITIES', 'Water/Electricity'), ('TELECOM', 'Phone/Internet'), ('RENT', 'Rent'), ('SERVICE', 'Services'), ('LOAN', 'Bank Loan'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
