# Generated by Django 4.2.16 on 2025-02-14 21:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0047_contract_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatconfiguration',
            name='default_forecast_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('400000.00'), help_text='Default amount for VAT forecasts', max_digits=15),
        ),
        migrations.AlterField(
            model_name='contract',
            name='invoice_type',
            field=models.CharField(choices=[('ENERGY', 'Energy'), ('INSURANCE', 'Insurance'), ('LEASING', 'Leasing'), ('UTILITIES', 'Water/Electricity'), ('TELECOM', 'Phone/Internet'), ('RENT', 'Rent'), ('SERVICE', 'Services'), ('LOAN', 'Bank Loan'), ('SOCIAL', 'Social Security'), ('RETIREMENT', 'Retirement'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('ENERGY', 'Energy'), ('INSURANCE', 'Insurance'), ('LEASING', 'Leasing'), ('UTILITIES', 'Water/Electricity'), ('TELECOM', 'Phone/Internet'), ('RENT', 'Rent'), ('SERVICE', 'Services'), ('LOAN', 'Bank Loan'), ('SOCIAL', 'Social Security'), ('RETIREMENT', 'Retirement'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
