# Generated by Django 4.2.16 on 2025-02-16 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0048_vatconfiguration_default_forecast_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankfeetransaction',
            name='vat_declaration_period',
            field=models.CharField(blank=True, help_text='VAT Declaration period (MM-YYYY)', max_length=7, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{4}$', 'Period must be in MM-YYYY format')]),
        ),
        migrations.AddField(
            model_name='bankfeetransaction',
            name='vat_declared',
            field=models.BooleanField(default=False),
        ),
    ]
