# Generated by Django 4.2.16 on 2025-02-16 22:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0049_bankfeetransaction_vat_declaration_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_code', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^2\\d{3,4}$', 'Asset account must start with 2 and have 4-5 digits')])),
                ('depreciation_account', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^2\\d{3,4}$', 'Depreciation account must start with 2 and have 4-5 digits')])),
                ('allowance_account', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^6\\d{3,4}$', 'Allowance account must start with 6 and have 4-5 digits')])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('depreciation_period', models.IntegerField(help_text='Depreciation period in years', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
            ],
            options={
                'verbose_name': 'Asset Account',
                'verbose_name_plural': 'Asset Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invoiceproduct',
            name='treated_as_asset',
            field=models.BooleanField(default=False, help_text='Indicates if this product was treated as an asset in this invoice'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_asset',
            field=models.BooleanField(default=False, help_text='If true, this product is treated as an asset'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'is_asset'), name='unique_product_name_per_type'),
        ),
        migrations.AddField(
            model_name='product',
            name='asset_account',
            field=models.ForeignKey(blank=True, help_text='Required if product is an asset', null=True, on_delete=django.db.models.deletion.PROTECT, to='testapp.assetaccount'),
        ),
    ]
