# Generated by Django 4.2.16 on 2025-02-20 20:24

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0050_assetaccount_invoiceproduct_treated_as_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_code', models.CharField(help_text='Main account code for cash operations', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{4,5}$', 'Account code must be 4-5 digits')])),
                ('journal_code', models.CharField(default='08', max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', 'Journal must be exactly 2 digits')])),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('max_payment_threshold', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='cash_payment_allowed',
            field=models.BooleanField(default=False, help_text='If True, this invoice can be paid by cash'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expense_code',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField()),
                ('reference', models.CharField(help_text='Unique reference number for this payment', max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('vat_declared', models.BooleanField(default=False)),
                ('vat_declaration_period', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{4}$', 'Period must be in MM-YYYY format')])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_payments', to='testapp.invoice')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('reference', models.CharField(help_text='Unique reference number for this expense', max_length=50, unique=True)),
                ('expense_account', models.CharField(help_text='Expense account code', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{4,5}$', 'Account code must be 4-5 digits')])),
                ('expense_type', models.CharField(choices=[('FINE', 'Fines'), ('FOOD', 'Food'), ('TAXI', 'Transportation'), ('OTHER', 'Other Expenses')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('reference', models.CharField(help_text='Unique reference number for this deposit', max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
