# Generated by Django 4.2.16 on 2025-02-25 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0051_cashconfiguration_invoice_cash_payment_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdeposit',
            name='source_account_code',
            field=models.CharField(blank=True, help_text='Accounting code for the source account', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cashdeposit',
            name='source_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_withdrawals', to='testapp.bankaccount'),
        ),
        migrations.AddField(
            model_name='cashdeposit',
            name='source_type',
            field=models.CharField(choices=[('bank', 'Bank Account'), ('other', 'Other Source')], default='other', max_length=10),
        ),
    ]
