# Generated by Django 4.2.16 on 2025-03-01 10:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0052_cashdeposit_source_account_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadingrecord',
            options={'ordering': ['-loading_date'], 'verbose_name': 'Loading Record', 'verbose_name_plural': 'Loading Records'},
        ),
        migrations.RemoveField(
            model_name='loadingrecord',
            name='brick_type',
        ),
        migrations.RemoveField(
            model_name='loadingrecord',
            name='bulk_price',
        ),
        migrations.RemoveField(
            model_name='loadingrecord',
            name='bulk_quantity',
        ),
        migrations.RemoveField(
            model_name='loadingrecord',
            name='packaged_price',
        ),
        migrations.RemoveField(
            model_name='loadingrecord',
            name='packaged_quantity',
        ),
        migrations.CreateModel(
            name='LoadingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulk_quantity', models.PositiveIntegerField(default=0)),
                ('packaged_quantity', models.PositiveIntegerField(default=0)),
                ('breakage', models.PositiveIntegerField(default=0)),
                ('bulk_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('packaged_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('brick_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.bricktype')),
                ('loading_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='testapp.loadingrecord')),
            ],
            options={
                'ordering': ['brick_type__name'],
                'unique_together': {('loading_record', 'brick_type')},
            },
        ),
    ]
