# Generated by Django 4.2.16 on 2025-03-07 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0053_alter_loadingrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBankRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('bank_label', models.CharField(help_text='Label that will appear on the bank statement', max_length=255)),
                ('accounting_label', models.CharField(help_text='Label that will appear in accounting entries', max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to debit (outgoing)', max_digits=15, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to credit (incoming)', max_digits=15, null=True)),
                ('account_code', models.CharField(help_text='Accounting code for this entry', max_length=10)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_records', to='testapp.bankaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_bank_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
