# Generated by Django 4.2.16 on 2025-03-07 22:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0054_custombankrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_code', models.CharField(default='44525', help_text='Accounting code for IR operations', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{4,10}$', 'Account code must be 4-10 digits')])),
                ('journal_code', models.CharField(default='05', max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', 'Journal must be exactly 2 digits')])),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default IR amount for forecasts', max_digits=15)),
                ('declaration_day', models.PositiveSmallIntegerField(default=20, help_text='Day of the month when IR declarations are due', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Bi-annual'), ('annual', 'Annual')], default='monthly', help_text='Frequency of IR declarations', max_length=10)),
                ('domiciliation_bank', models.ForeignKey(help_text='Bank account used for IR payments', on_delete=django.db.models.deletion.PROTECT, related_name='ir_declarations', to='testapp.bankaccount')),
            ],
            options={
                'verbose_name': 'IR Configuration',
                'verbose_name_plural': 'IR Configuration',
            },
        ),
        migrations.CreateModel(
            name='IRDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('period_year', models.PositiveSmallIntegerField()),
                ('salary_amount', models.DecimalField(decimal_places=2, help_text='Total salary amount', max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='Total IR tax amount', max_digits=15)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('declared', 'Declared'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='declared', max_length=10)),
                ('payment_date', models.DateField(blank=True, help_text='Date when the declaration was paid', null=True)),
                ('rejection_date', models.DateField(blank=True, help_text='Date when the declaration was rejected', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ir_declaration', to='testapp.forecaststatement')),
            ],
            options={
                'verbose_name': 'IR Declaration',
                'verbose_name_plural': 'IR Declarations',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('period_month', 'period_year')},
            },
        ),
    ]
