# Generated by Django 4.2.16 on 2025-03-07 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0055_irconfiguration_irdeclaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irconfiguration',
            name='declaration_day',
            field=models.PositiveSmallIntegerField(default=20, help_text='Day of the month when IR declarations are due', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
