# Generated by Django 4.2.16 on 2025-03-12 00:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0056_alter_irconfiguration_declaration_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='StampRightConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_code', models.CharField(default='44526', help_text='Accounting code for Stamp Rights operations', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{4,10}$', 'Account code must be 4-10 digits')])),
                ('journal_code', models.CharField(default='06', max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', 'Journal must be exactly 2 digits')])),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default Stamp Rights amount for forecasts', max_digits=15)),
                ('declaration_day', models.PositiveSmallIntegerField(default=20, help_text='Day of the month when Stamp Rights declarations are due', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.25'), help_text='Tax rate percentage for Stamp Rights', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('10.00'))])),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Bi-annual'), ('annual', 'Annual')], default='monthly', help_text='Frequency of Stamp Rights declarations', max_length=10)),
                ('domiciliation_bank', models.ForeignKey(help_text='Bank account used for Stamp Rights payments', on_delete=django.db.models.deletion.PROTECT, related_name='stamp_rights_declarations', to='testapp.bankaccount')),
            ],
            options={
                'verbose_name': 'Stamp Rights Configuration',
                'verbose_name_plural': 'Stamp Rights Configuration',
            },
        ),
        migrations.CreateModel(
            name='StampRightDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('period_year', models.PositiveSmallIntegerField()),
                ('invoices_amount', models.DecimalField(decimal_places=2, help_text='Total amount of invoices paid in cash', max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='Total Stamp Rights tax amount', max_digits=15)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('declared', 'Declared'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='declared', max_length=10)),
                ('payment_date', models.DateField(blank=True, help_text='Date when the declaration was paid', null=True)),
                ('rejection_date', models.DateField(blank=True, help_text='Date when the declaration was rejected', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stamp_right_declaration', to='testapp.forecaststatement')),
            ],
            options={
                'verbose_name': 'Stamp Rights Declaration',
                'verbose_name_plural': 'Stamp Rights Declarations',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('period_month', 'period_year')},
            },
        ),
    ]
