# Generated by Django 4.2.16 on 2025-03-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0058_stamprightdeclaration_rejection_cause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irdeclaration',
            name='rejection_cause',
            field=models.CharField(blank=True, choices=[('INSUFFICIENT_FUNDS', 'Insufficient Funds'), ('ACCOUNT_CLOSED', 'Account Closed/Frozen'), ('SIGNATURE_MISMATCH', 'Signature Mismatch'), ('TECHNICAL_ERROR', 'Technical Error'), ('BANK_ERROR', 'Bank Processing Error'), ('OTHER', 'Other')], help_text='Reason for rejection', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='irdeclaration',
            name='rejection_notes',
            field=models.TextField(blank=True, help_text='Additional notes about rejection'),
        ),
    ]
