# Generated by Django 4.2.16 on 2025-03-14 00:05

from django.db import migrations, models
import testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0059_irdeclaration_rejection_cause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irdeclaration',
            name='declaration_document',
            field=models.FileField(blank=True, help_text='Upload declaration receipt', null=True, upload_to=testapp.models.get_upload_path, validators=[testapp.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='irdeclaration',
            name='payment_document',
            field=models.FileField(blank=True, help_text='Upload payment receipt', null=True, upload_to=testapp.models.get_upload_path, validators=[testapp.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='stamprightdeclaration',
            name='declaration_document',
            field=models.FileField(blank=True, help_text='Upload declaration receipt', null=True, upload_to=testapp.models.get_upload_path, validators=[testapp.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='stamprightdeclaration',
            name='payment_document',
            field=models.FileField(blank=True, help_text='Upload payment receipt', null=True, upload_to=testapp.models.get_upload_path, validators=[testapp.models.validate_file_size]),
        ),
    ]
