# Generated by Django 4.2.16 on 2025-03-15 00:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import testapp.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0060_irdeclaration_declaration_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherTaxDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_type', models.CharField(choices=[('professional', 'Professional Tax'), ('communal', 'Communal Tax')], help_text='Type of tax', max_length=20)),
                ('year', models.PositiveSmallIntegerField(help_text='Tax year')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total tax amount', max_digits=15)),
                ('due_date', models.DateField(help_text='Date when the tax is due')),
                ('status', models.CharField(choices=[('declared', 'Declared'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='declared', max_length=15)),
                ('payment_method', models.CharField(blank=True, choices=[('direct_debit', 'Direct Debit'), ('check', 'Check'), ('lcn', 'LCN'), ('cash', 'Cash')], help_text='Method used to pay the tax', max_length=15, null=True)),
                ('payment_date', models.DateField(blank=True, help_text='Date when the tax was paid', null=True)),
                ('rejection_cause', models.CharField(blank=True, choices=[('INSUFFICIENT_FUNDS', 'Insufficient Funds'), ('ACCOUNT_CLOSED', 'Account Closed/Frozen'), ('SIGNATURE_MISMATCH', 'Signature Mismatch'), ('TECHNICAL_ERROR', 'Technical Error'), ('BANK_ERROR', 'Bank Processing Error'), ('OTHER', 'Other')], help_text='Reason for rejection', max_length=20, null=True)),
                ('rejection_notes', models.TextField(blank=True, help_text='Additional notes about rejection')),
                ('rejection_date', models.DateField(blank=True, help_text='Date when the payment was rejected', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('tax_notice_document', models.FileField(blank=True, help_text='Upload tax notice document', null=True, upload_to=testapp.models.get_upload_path, validators=[testapp.models.validate_file_size])),
                ('payment_receipt_document', models.FileField(blank=True, help_text='Upload payment receipt document', null=True, upload_to=testapp.models.get_upload_path, validators=[testapp.models.validate_file_size])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount already paid', max_digits=15)),
                ('forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_tax_declaration', to='testapp.forecaststatement')),
            ],
            options={
                'verbose_name': 'Other Tax Declaration',
                'verbose_name_plural': 'Other Tax Declarations',
                'ordering': ['-year'],
                'unique_together': {('tax_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TaxFine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fine amount', max_digits=15)),
                ('fine_date', models.DateField(default=django.utils.timezone.now, help_text='Date when the fine was applied')),
                ('reference', models.CharField(blank=True, help_text='Reference number or code for the fine', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description or reason for the fine')),
                ('paid', models.BooleanField(default=False, help_text='Whether the fine has been paid')),
                ('payment_date', models.DateField(blank=True, help_text='Date when the fine was paid', null=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='testapp.othertaxdeclaration')),
            ],
            options={
                'verbose_name': 'Tax Fine',
                'verbose_name_plural': 'Tax Fines',
            },
        ),
        migrations.CreateModel(
            name='OtherTaxConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_type', models.CharField(choices=[('professional', 'Professional Tax'), ('communal', 'Communal Tax')], help_text='Type of tax', max_length=20, unique=True)),
                ('accounting_code', models.CharField(help_text='Accounting code for tax operations', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{4,10}$', 'Account code must be 4-10 digits')])),
                ('journal_code', models.CharField(help_text='Journal code for accounting entries', max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', 'Journal must be exactly 2 digits')])),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default tax amount for forecasts', max_digits=15)),
                ('due_month', models.PositiveSmallIntegerField(help_text='Month when the tax is due', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('due_day', models.PositiveSmallIntegerField(default=20, help_text='Day of the month when tax declarations are due', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('fines_accounting_code', models.CharField(help_text='Accounting code for tax fines', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{4,10}$', 'Account code must be 4-10 digits')])),
                ('domiciliation_bank', models.ForeignKey(blank=True, help_text='Bank account used for tax payments if using direct debit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_tax_configurations', to='testapp.bankaccount')),
            ],
            options={
                'verbose_name': 'Other Tax Configuration',
                'verbose_name_plural': 'Other Tax Configurations',
            },
        ),
    ]
