# Generated by Django 4.2.16 on 2025-03-15 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0061_othertaxdeclaration_taxfine_othertaxconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='othertaxconfiguration',
            name='forecast_bank',
            field=models.ForeignKey(blank=True, help_text='Bank account used for tax payment forecasts', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_tax_forecasts', to='testapp.bankaccount'),
        ),
    ]
