# Generated by Django 4.2.16 on 2025-03-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0062_othertaxconfiguration_forecast_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='is_tax_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='tax_declaration_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='tax_declaration_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
