# Generated by Django 4.2.16 on 2025-03-17 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('testapp', '0063_check_is_tax_payment_check_tax_declaration_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_checks', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='check',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
