# Generated by Django 4.2.16 on 2025-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0064_check_content_type_check_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='othertaxdeclaration',
            options={'ordering': ['-year', '-created_at'], 'verbose_name': 'Other Tax Declaration', 'verbose_name_plural': 'Other Tax Declarations'},
        ),
        migrations.AlterUniqueTogether(
            name='othertaxdeclaration',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stamprightdeclaration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='othertaxdeclaration',
            name='reference',
            field=models.CharField(blank=True, help_text='Unique reference for this declaration', max_length=50, null=True, unique=True),
        ),
    ]
