# Generated by Django 4.2.16 on 2025-04-10 23:52

import django.core.validators
from django.db import migrations, models
import testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0065_alter_othertaxdeclaration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='document',
            field=models.FileField(blank=True, help_text='Upload check document', null=True, upload_to=testapp.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), testapp.models.validate_file_size]),
        ),
    ]
