# Generated by Django 4.2.16 on 2025-04-11 17:59

import django.core.validators
from django.db import migrations, models
import testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0066_check_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='document',
            field=models.FileField(blank=True, help_text='Upload contract document', null=True, upload_to=testapp.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), testapp.models.validate_file_size]),
        ),
    ]
