# Generated by Django 4.2.16 on 2025-04-11 18:58

import django.core.validators
from django.db import migrations, models
import testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0067_contract_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='regulation_file_path',
        ),
        migrations.AddField(
            model_name='supplier',
            name='email_primary',
            field=models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$', 'Enter a valid email address.')]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email_secondary',
            field=models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$', 'Enter a valid email address.')]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_delay_file',
            field=models.FileField(blank=True, help_text='Upload payment delay agreement file', null=True, upload_to=testapp.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), testapp.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{8,15}$', 'Enter a valid phone number.')]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{8,15}$', 'Enter a valid phone number.')]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='regulation_file',
            field=models.FileField(blank=True, help_text='Upload supplier regulation file', null=True, upload_to=testapp.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), testapp.models.validate_file_size]),
        ),
    ]
