# Generated by Django 4.2.16 on 2025-04-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0068_remove_supplier_regulation_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='internal_reference',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
    ]
